# Basic Settings
log_path: "./logs/"
version: "rgb-30envs-pointnav"
resume: False
pretrained: False
load_path: 

# Environment Settings
env:
  env_paths: [
   "envs/city-env/0000/env.x86_64",
   "envs/city-env/0001/env.x86_64",
   "envs/city-env/0003/env.x86_64",
   "envs/city-env/0004/env.x86_64",
   "envs/city-env/0005/env.x86_64",
   "envs/city-env/0006/env.x86_64",
   "envs/city-env/0008/env.x86_64",
   "envs/city-env/0009/env.x86_64",
   "envs/city-env/0010/env.x86_64",
   "envs/city-env/0014/env.x86_64",
   "envs/city-env/0015/env.x86_64",
   "envs/city-env/0017/env.x86_64",
   "envs/city-env/0019/env.x86_64",
   "envs/city-env/0020/env.x86_64",
   "envs/city-env/0021/env.x86_64",
   "envs/city-env/0022/env.x86_64",
   "envs/city-env/0024/env.x86_64",
   "envs/city-env/0025/env.x86_64",
   "envs/city-env/0026/env.x86_64",
   "envs/city-env/0027/env.x86_64",
   "envs/city-env/0028/env.x86_64",
   "envs/city-env/0030/env.x86_64",
   "envs/city-env/0034/env.x86_64",
   "envs/city-env/0035/env.x86_64",
   "envs/city-env/0036/env.x86_64",
   "envs/city-env/0038/env.x86_64",
   "envs/city-env/0039/env.x86_64",
   "envs/city-env/0042/env.x86_64",
   "envs/city-env/0043/env.x86_64",
   "envs/city-env/0044/env.x86_64",
  ]
  test_env_paths: [
    "" # Test env path goes here
  ]
  env_class: 'subproc'
  seed: 0
  time_scale: 10.0
  screen_width: 640
  screen_height: 360 

  obs_width: 128
  obs_height: 72
  
  max_episode_length: 60
  time_penalty_multiplier: -0.1
  distance_reward_multiplier: 1
  steer_smooth_reward_multiplier: 0.05
  collision_penalty: -1
  goal_reward: 10
  fail_reward: -10
  random_obj_placement: True
  max_loaded_obj_num: 1
  collision_limit: 5
  enable_dynamic_agent: False
  dynamic_agent_n: 1
  
  use_rgb: True
  use_depth: False

# Training Settings
train:
  type: "sac" # Supported algorithms: ppo, sac
  verbose: 1
  total_timesteps: 3000000
  save_freq: 100000
  train_freq: 1
  train_freq_unit: step

  feature_extractor:
    name: "cnn"
    base_channel: 16
    encode_dim: 128

  net_arch:
    size: 128

  trainer:
    learning_starts: 10000
    tau: 0.005
    gamma: 0.99 
    buffer_size: 102400
    sde_sample_freq: 64
    batch_size: 256
    learning_rate: 0.0003
    ent_coef: auto
    use_sde_at_warmup: True
    use_sde: True

eval:
  enabled: True
  start_at: 500000
  freq: 50000
  n_episodes: 5
  work_id: 10

inference:
  num_episodes: 25
  render: True
  render_freq: 1
  max_steps: 9999
  decision_freq: 1
  plot_path: "plots/"
  video_path: "videos/"
  fps: 5

inference:
  num_episodes: 25
  render: True
  render_freq: 1
  max_steps: 1000
  decision_freq: 10
  plot_path: "plots/"
  video_path: "videos/"
  fps: 30

