# Basic Settings
log_path: "./logs/"
version: "rgb-30envs-socialnav"
resume: False
pretrained: False
load_path: 

# Environment Settings
env:
  env_paths: [
   "envs/dynamic/00/env.x86_64",
   "envs/dynamic/01/env.x86_64",
   "envs/dynamic/02/env.x86_64",
   "envs/dynamic/03/env.x86_64",
   "envs/dynamic/04/env.x86_64",
   "envs/dynamic/05/env.x86_64",
   "envs/dynamic/06/env.x86_64",
   "envs/dynamic/07/env.x86_64",
   "envs/dynamic/08/env.x86_64",
   "envs/dynamic/09/env.x86_64",
   "envs/dynamic/10/env.x86_64",
   "envs/dynamic/11/env.x86_64",
   "envs/dynamic/12/env.x86_64",
   "envs/dynamic/13/env.x86_64",
   "envs/dynamic/14/env.x86_64",
   "envs/dynamic/15/env.x86_64",
   "envs/dynamic/16/env.x86_64",
   "envs/dynamic/17/env.x86_64",
   "envs/dynamic/18/env.x86_64",
   "envs/dynamic/19/env.x86_64",
   "envs/dynamic/20/env.x86_64",
   "envs/dynamic/21/env.x86_64",
   "envs/dynamic/22/env.x86_64",
   "envs/dynamic/23/env.x86_64",
   "envs/dynamic/24/env.x86_64",
   "envs/dynamic/25/env.x86_64",
   "envs/dynamic/26/env.x86_64",
   "envs/dynamic/27/env.x86_64",
   "envs/dynamic/28/env.x86_64",
   "envs/dynamic/29/env.x86_64",
  ]
  test_env_paths: [
    "envs/dynamic/00/env.x86_64", # Test env goes here
  ]
  unity_args:
    - "-batchmode"
    - "-force-vulkan"
    - "-screen-width=1280"
    - "-screen-height=720"
  env_class: 'subproc'
  seed: 1
  time_scale: 10.0
  screen_width: 128
  screen_height: 72 

  obs_width: 128
  obs_height: 72
  
  max_episode_length: 60
  time_penalty_multiplier: -0.1
  distance_reward_multiplier: 1
  steer_smooth_reward_multiplier: 0.05
  collision_penalty: -1
  goal_reward: 10
  fail_reward: -10
  random_obj_placement: True
  max_loaded_obj_num: 1
  collision_limit: 5
  enable_dynamic_agent: True
  dynamic_agent_n: 1
  
  use_rgb: True
  use_depth: False

# Training Settings
train:
  type: "sac" # Supported algorithms: ppo, sac
  verbose: 1
  total_timesteps: 3000000
  save_freq: 100000
  train_freq: 1
  train_freq_unit: step

  feature_extractor:
    name: "cnn"
    base_channel: 16
    encode_dim: 128

  net_arch:
    size: 128

  trainer:
    learning_starts: 10000
    tau: 0.005
    gamma: 0.99 
    buffer_size: 102400
    sde_sample_freq: 64
    batch_size: 256
    learning_rate: 0.0003
    ent_coef: auto
    use_sde_at_warmup: True
    use_sde: True

eval:
  enabled: True
  start_at: 500000
  freq: 50000
  n_episodes: 5
  work_id: 2048

inference:
  num_episodes: 25
  render: True
  render_freq: 1
  max_steps: 9999
  decision_freq: 1
  plot_path: "plots/"
  video_path: "videos/"
  fps: 5

